name: NeAF
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - basemap=1.2.2
  - blas=1.0
  - brotli=1.0.9
  - c-ares=1.18.1
  - ca-certificates=2022.3.29
  - certifi=2021.10.8
  - cudatoolkit=11.3.1
  - cycler=0.11.0
  - dbus=1.13.18
  - expat=2.4.4
  - fontconfig=2.13.1
  - fonttools=4.25.0
  - freetype=2.11.0
  - geos=3.8.1
  - giflib=5.2.1
  - glib=2.69.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - intel-openmp=2021.4.0
  - joblib=1.1.0
  - jpeg=9d
  - kiwisolver=1.3.2
  - krb5=1.19.2
  - lcms2=2.12
  - ld_impl_linux-64=2.35.1
  - libcurl=7.82.0
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libgomp=9.3.0
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.19.1
  - libssh2=1.9.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.2.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.14
  - libxml2=2.9.12
  - lz4-c=1.9.3
  - matplotlib=3.4.3
  - matplotlib-base=3.4.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - munkres=1.1.4
  - ncurses=6.3
  - numpy=1.21.5
  - numpy-base=1.21.5
  - openssl=1.1.1n
  - pcre=8.45
  - pillow=9.0.1
  - pip=21.2.2
  - proj=7.1.1
  - protobuf=3.19.1
  - pyparsing=3.0.4
  - pyproj=2.6.1.post1
  - pyqt=5.9.2
  - pyshp=2.1.3
  - python=3.7.11
  - python-dateutil=2.8.2
  - python_abi=3.7
  - pytorch=1.10.0
  - pytorch-mutex=1.0
  - qt=5.9.7
  - readline=8.1.2
  - scikit-learn=1.0.1
  - scipy=1.7.3
  - setuptools=61.2.0
  - sip=4.19.8
  - six=1.16.0
  - sqlite=3.38.2
  - tensorboardx=2.2
  - threadpoolctl=2.2.0
  - tk=8.6.11
  - tornado=6.1
  - typing_extensions=4.1.1
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.4.9
